
/* Error values */
enum resolve_err_t { 
	
	RESOLVEERR_FAIL = -1,
	RESOLVE_ERR_SUCCESS = 0,
	RESOLVE_ERR_NOCARD = 1,
	RESOLVE_ERR_IFDOWN = 2,
	RESOLVE_ERR_MACZERO = 3,
	RESOLVE_ERR_UNASSOCIATED = 4,
	RESOLVE_ERR_UNCONFIGURED = 5,
	RESOLVE_ERR_WITHOUT_IP = 6,
	RESOLVE_ERR_DIE_UDHCPC = 7,
	RESOLVE_ERR_PUB_NET_REFUSE = 8,
	RESOLVE_ERR_DNS_FAIL = 9,
	RESOLVE_ERR_FIREWALL_BLOCKED = 10,
};




