/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_norco_utils_GpioJNI */

#ifndef _Included_com_norco_utils_GpioJNI
#define _Included_com_norco_utils_GpioJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_norco_utils_GpioJNI
 * Method:    getSum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_norco_utils_GpioJNI_getSum
  (JNIEnv *, jclass);

/*
 * Class:     com_norco_utils_GpioJNI
 * Method:    getLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_norco_utils_GpioJNI_getLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_norco_utils_GpioJNI
 * Method:    setLevel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_norco_utils_GpioJNI_setLevel
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
